### PR TITLE
Added various icons for scripts used in the VRC Community

### PR DESCRIPTION
**Pull request by JustBuddy**
AudioLink and GestureManager are from icons8.com, LTCGI and VRCFury from their respective maintainers.

### CODE REVIEW

**Comment by Dreadrith** [comment]
To follow up with the purpose of the pull request, VRCWorld components icons were also requested. Would you want to add some  too or leave it for someone else and just merge this?

**Comment by JustBuddy** [comment]
I can look into that for sure, I'll update this PR once I get to it.

**Comment by JustBuddy** [comment]
@Dreadrith Submitted commit 878b98e with requested and some additional icons, all from Icons8.
VRCSceneDescriptor, UdonBehaviour, and some for QVPen.

**Comment by Dreadrith** [comment]
Thank you for your contribution! 
I'm also going to check the code and modify it, if need be, so that they can be categorized into folders to make it less daunting.

**Pull request merged**
